AIC Poisson/Neg-Bin Implementation
SyndemicsLab/Syndemics pull request #1
Opened 2023-07-31 15:46 UTC by ryan-odea

Added
- Formula_List, develops list of possible formulas given strings
- AIC methodology for Poisson and Negative Binomial Regression off of the brute force formula_list creation
- At convergence failure the `crc` function will report the error and then continue on with the rest of the brute force methods

Fixed
- Removed named numerics output from `confint()` = looks nicer, a little nicer to work with on the user side
- Removed `confint` spam into the console
- Fixed a spelling error :)

2023-07-31 18:07 UTC, ddbaptiste approved these changes

2023-08-02 15:36 UTC, MJC598 approved these changes

2023-08-03 12:25 UTC, MJC598 commented on R/crc.R
> +  if(is.null(formula)){
This checks to verify formula is null and then the nested if statements uses formula, wouldn't the nested if statements require it to be is.not.null(formula) to work?

2023-08-03 12:28 UTC, MJC598 requested changes
Just the one comment, but it seems like it could force no formula on the data

2023-08-03 12:28 UTC, MJC598 commented on R/crc.R
> +  if(is.null(formula)){
This checks to verify formula is null and then the nested if statements uses formula, wouldn't the nested if statements require it to be is.not.null(formula) to work?

2023-08-03 14:02 UTC, MJC598 approved these changes

2023-08-03 14:52 UTC, merged

2023-08-03 16:31 UTC, MJC598 reviewed
Cool