Building Life Tables from CDC US Data
SyndemicsLab/Syndemics pull request #15
Opened 2024-10-22 12:58 UTC by MJC598

@ryan-odea This PR is intended to utilize the data directly from the CDC NVSS Life Tables (per year stratified by a/r/s) and convert it into the background_mortality file used in RESPOND. I am questioning a clean way to pass the directory, output file, and stratifications to the functions but all absolute paths have been removed.

2025-01-24 23:08 UTC, ryan-odea requested changes
Small changes since I imaging this will fail the CMD check now, and then talking with you ion the change of import

2025-01-24 23:08 UTC, ryan-odea commented on Syndemics/NAMESPACE
@MJC598 Somewhat of a personal preference, but I don't like seeing `tidyverse` used as an import since it's a collection of packages, we can probably just `importFrom tidyr crossing` or (assuming this is making a cross join) use `dplyr::cross_join` for something a little more explicit

2025-01-24 23:08 UTC, ryan-odea commented on Syndemics/R/buildLifeTables.R
I suspect some of these will be met with a bad NOTE when running `devtools::check()` because of how data.table work with it's syntax -
`DT <- DT[, myVar := 1]` will return an error
```
myVar <- NULL
DT <- DT[, myVar := 1]

OR
DT <- DT[, "myVar" := 1]
``` 
scoots around the flag

2025-01-27 16:29 UTC, MJC598 commented on Syndemics/R/buildLifeTables.R
Addressed in [d399598](https://github.com/SyndemicsLab/Syndemics/pull/15/commits/d3995981640be992cf2b533e476ea9e92667fb41)

2025-01-27 16:29 UTC, MJC598 commented on Syndemics/NAMESPACE
Addressed in [d399598](https://github.com/SyndemicsLab/Syndemics/pull/15/commits/d3995981640be992cf2b533e476ea9e92667fb41)

2025-01-27 22:32 UTC, ryan-odea approved these changes
Looks good!

2025-01-28 13:59 UTC, merged